### ISSUE TITLE
Usage as a pager

### ISSUE THREAD

**Issue by DrPyser** [eburghar/kakpipe#3]
Hi, nice work!

Is there a simple way to use kakoune as a pager using kakpipe? 

That is, instead of launching a program from inside kakoune, creating a pipeline that processes stdin into the kakpipe managed fifo buffer?

Thanks!

**Comment by eburghar** [comment]
Hi DrPyser,

You probably have to use a fifo you can read from

```bash
mkfifo /tmp/pager
```

and then launch your script inside kakoune that read from that fifo

```
:kakpipe -n pager -- sh -c 'while true; do if read line; then echo $line; fi; done </tmp/pager'
```

then you can just send lines to `/tmp/pager` from outside

```bash
echo -e '\e[30;41malert' >/tmp/pager
```

If you want to launch kakpipe outside of kakoune you need a client and session ids:

```bash
echo "eval -client $KAKOUNE_CLIENT 'kakpipe -n pager -- ls -l /tmp'" | kak -p $KAKOUNE_SESSION
```
